In [1]:
import numpy as np
import cv2

# FACE DETECTION

In [88]:
img = cv2.imread('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/testing_images/testing_image.jpg')
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [80]:
#Load cascade classifer - frontalface
face_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_frontalface_default.xml')


In [95]:
#apply cascade classifer to an image
faces, num_detection = face_cascade.detectMultiScale2(img, minNeighbors=5, scaleFactor=1.12, minSize=(30,30))

In [96]:
print(faces) #The coordinates of the detected faces basically is a rectangle around the face

[[369 504 267 267]
 [591 872 258 258]]


In [97]:
print(num_detection) #The number of points that were matched to detect the face

[18 10]


In [98]:
for x, y, w, h in faces:
    pt1 = (x, y)
    pt2 = (x + w, y + h)
    cv2.rectangle(img, pt1, pt2, (255, 0, 0), 2)  # Blue rectangles

cv2.imshow('image', img)
cv2.waitKey(0) & 0xFF
cv2.destroyAllWindows()

In [32]:
#Draw the circle
cx = x + w//2 #Center x coordinate calculates by: the x position of the face + the width of the face divided by 2
cy = y + h//2 #Center y coordinate calculates by: the y position of the face + the height of the face divided by 2
r = w//2 #Radius of the circle is the width of the face divided by 2

cv2.circle(img, (cx,cy), r, (0,255,0), 3)
cv2.imshow('face detection circle', img)
key = cv2.waitKey(0) & 0xFF
if key == ord('q'):
    cv2.destroyAllWindows()

# Multiple Faces Detection


In [160]:
img = cv2.imread('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/testing_images/friends_img.jpg')


cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [165]:
face_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_frontalface_default.xml')
profile_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_profileface.xml')

faces_frontal, num_detection_frontal = face_cascade.detectMultiScale2(img, minNeighbors=2, scaleFactor=1.05, minSize=(10,10))

faces_profile , num_detection_profile = profile_cascade.detectMultiScale2(img, minNeighbors=2, scaleFactor=1.05, minSize=(10,10))


#Draw the rectangle around the face_profiles
for x, y, w, h in faces_frontal:
    pt1 = (x, y)
    pt2 = (x + w, y + h)
    cv2.rectangle(img, pt1, pt2, (255, 0, 0), 1)  # Blue rectangles


print(faces_frontal)
print(faces_profile)
# cv2.imshow('image', img)
# cv2.waitKey(0) & 0xFF
# cv2.destroyAllWindows()

[[162  22  37  37]
 [219  32  50  50]
 [ 98  24  57  57]]
[[166  19  42  42]
 [227  31  51  51]
 [104  21  66  66]]


# Faces & Eyes Detection


In [5]:
img = cv2.imread('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/testing_images/testing_image.jpg')

In [78]:
face_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_eye.xml')

In [79]:
faces, num_detection = face_cascade.detectMultiScale2(img, scaleFactor=1.1, minSize=(10,10), minNeighbors=5)
print(num_detection)
for x,y,w,h in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0))

    #Cropping the face
    face_roi = img[y:y+h, x:x+w] #Region of interest used for cropping the image, where the row goes first and then the column so then the y coordinate goes first and then the x coordinate
    #apply cascade classifer to eyes
    eyes, num_detection_eyes = eye_cascade.detectMultiScale2(face_roi, scaleFactor=1.1, minSize=(10,10), minNeighbors=4)
    print(num_detection_eyes)
    #Draw the circle around the eyes
    for ex,ey,ew,eh in eyes:
        cx = x + ex + ew//2 #Add x since we need the entire image coordinates
        cy = y + ey + eh//2 #Add y since we need the entire image coordinates
        r = eh//2 
        cv2.circle(img, (cx,cy), r, (0,255,0), 2)

# #Display the image
cv2.imshow('face, eyes detection', img)
cv2.waitKey(0) & 0xFF
cv2.destroyAllWindows()

[8 9]
[29 19]
[48]


# Face, Eyes, Smile Detection

In [43]:
img = cv2.imread('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/testing_images/testing_image.jpg')

In [25]:
face_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_eye.xml')
smile_cascade = cv2.CascadeClassifier('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/cascades/haarcascade_smile.xml')

In [44]:
faces, num_detection = face_cascade.detectMultiScale2(img, scaleFactor=1.1, minSize=(10,10), minNeighbors=5)
print(num_detection)


for x,y,w,h in faces[0:1]:
    face_roi = img[y:y+h, x:x+w].copy() #Region of interest used for cropping the image, where the row goes first and then the column so then the y coordinate goes first and then the x coordinate
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0))

    #apply cascade classifer to eyes
    eyes, num_detection_eyes = eye_cascade.detectMultiScale2(face_roi, scaleFactor=1.1, minSize=(10,10), minNeighbors=4)
    print(num_detection_eyes)
    #Draw the circle around the eyes
    for ex,ey,ew,eh in eyes:
        cx = x + ex + ew//2 #Add x since we need the entire image coordinates
        cy = y + ey + eh//2 #Add y since we need the entire image coordinates
        r = eh//2 
        cv2.circle(img, (cx,cy), r, (0,255,0), 2)

    #apply cascade classifer to smile
    smile, num_detection_smile = smile_cascade.detectMultiScale2(face_roi, scaleFactor=1.2, minSize=(20,20), minNeighbors=8)
    for sx,sy,sw,sh in smile:
        cv2.rectangle(img,(x+sx, y + sy), (x+sx+sw, y+sy+sh), (0,255,0), 2) #the (x+sx+sw, y+sy+sh) is the diagonal line of the rectangle

    print(num_detection_smile)
#Display the image
cv2.imshow('face, eyes detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[8 9]
[29 19]
[80]


# Face Detection DNN

In [28]:
img = cv2.imread('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/data/testing_images/friends_img.jpg')

In [29]:
#load the model

net = cv2.dnn.readNetFromCaffe('/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/models/saved_models/deploy.prototxt.txt',
                                '/Users/ceo/Desktop/CTP_DATASCI_FRIDAY/final_project/server/models/saved_models/res10_300x300_ssd_iter_140000.caffemodel')

In [30]:
# Extract blob with DNN
blob = cv2.dnn.blobFromImage(img, 1, (300,300),  (104, 177, 123), swapRB=False)

In [31]:
# Pass the blob to model, set blob as input
net.setInput(blob)

In [32]:
# Run the model
detection = net.forward()

In [33]:
detection.shape

#1 , 1, 200 , 7 -> 200 is the faces detected, 7 is the number of: (0: Image number, 1: Binary(0,1), 2: Confidence Score (0 -1), 3-6: Bounding box coordinates(3: Start x, 4: Start y, 5: End x, 6: End y))

(1, 1, 200, 7)

In [34]:
h, w = img.shape[:2]

for i in range(0, detection.shape[2]):
    confidence = detection[0,0,i,2]
    if confidence > 0.5:
        box = detection[0,0,i,3:7] * np.array([w,h,w,h])
        (startX, startY, endX, endY) = box.astype('int')
        cv2.rectangle(img, (startX, startY), (endX, endY), (255,0,0), 2)

        #Put text
        cv2.putText(img, 'face: {:.2f}%'.format(confidence * 100), (startX, startY-10), cv2.FONT_HERSHEY_PLAIN, 0.45, (0,0,255),)
        print(confidence)
cv2.imshow('face detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

0.99997556
0.99990284
0.9700988
0.9383159


# Feature Extraction from Face